language: swift
osx_image: xcode12
all_branches: true
script:
  - rm -r ~/Library/Developer/Xcode/DerivedData
  - pod install --project-directory='iOS Example Frame'
  - xcodebuild test -workspace 'iOS Example Frame/iOS Example Frame.xcworkspace' -scheme 'Frames-Unit-Tests' -destination 'OS=13.5,name=iPhone 11'
  - xcodebuild build -project 'iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj' -scheme 'iOS Example Frame' -destination 'OS=13.5,name=iPhone 11'
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script: chmod +x ./scripts/push.sh && ./scripts/push.sh
  skip_cleanup: true
  on:
    tags: true
